In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
inverse = np.linalg.inv(array1)
multi = np.dot(array1,inverse)
multi

array([[1., 0.],
       [0., 1.]])

In [11]:
#運用上列array計算特徵值、特徵向量?
value , vector = np.linalg.eig(array1)
print('eigenvalues is \n',value)
print('eigenvector is \n',vector)

eigenvalues is 
 [13.  2.]
eigenvector is 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [14]:
#運用上列array計算SVD?
SVD = np.linalg.svd(array1)
print(SVD[0],'\n',SVD[1],'\n',SVD[2])

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 
 [13.94721714  1.86417116] 
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
